# Use root/example user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  db:
    build:
      context: .
      dockerfile: Dockerfile_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cquLabManager
      POSTGRES_HOST_AUTH_METHOD: trust

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080